language: node_js

sudo: false

matrix:
    fast_finish: true
    include:
      - node_js: 4

cache:
    directories:
      - $HOME/.npm

install:
  - npm install

script:
  - node compile.js
  - git diff --exit-code
